language: ruby
deploy:
  provider: heroku
  api_key:
    secure: OhE+zVLkvzPFQvQqKlmPVN5GepoFreVPSNR+blLf4Yga6pTy/HMkrOWPediRdTTrz0jzFuGlZQs4egzg6COaOPov8Zvtmm8wLti9qul5g0VXwHw+kMx9+OWXS/LHttY1noQNtD8fFSFWavP0x/OQzvJK4JToRBPqnbYcIae+0AQyd3WqncmrQYAjKhyyhXKKJRQIh6Rp0kcdgbV9U4UQqv86802hy2aPG9cKTip7DAnyOAPFCGZSIQjJHrOfrxwfgW03iJWytkp8YqZ4iNzKu/4u60rgLi8X5ImqYbM8G86l9yYj1g9JDBQm5otb2BSrvjG46Mhzjw6HfgZ2tA+sN1ItLv/FN49btSi39j6eHqsXIL2SCk04GMcFDhNLzupumog6b6YwT1m4JRxXKtrkXlaBYBOWFI/RPsuKhWURf+ibcgK7iBkzGDA6/4k73s3BWPDQmpSZdTgm6LpbyeUfWgUpO0mvcFSWRyMvQHwbw8Grr0wDpSMZbpiftlJ+Ef0JBZ/NQlwxO4vwwi+rHNkO3d5DaTNYuS+Z8hu8v9UMb89mk/Dd1CLO0XhOJvPSNuU6LSQMaccMnKaavQA0DzfJsx2spNmx9z6UsgbeU1aglLo9lLzkVp7kZaaDr9D9ReZ+zB4ch79VJOJMVNUzSDaPoowDx5p0q+OOUlfiLc4NteY=
  app: search-and-rescue-api
services:
- postgresql
script:
- bundle exec rails db:create
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
