language: ruby
deploy:
  provider: heroku
  api_key:
    secure: moVLGjp2p6d4dXYuSrHksRqFtG2pnE/MoAJG3CCK/xjKsWtEd8uSM8g/N5qT4UIIu+d0bXSJ/qFj6kd2Xf4ZT/jYjGUjIhVjvXnT2ilY25SllVCW5Oj9pdZtRgEcZaDf77GbS6sQqNGao/oqzVZRAf7BZkzueppUAOdFmIiLRMm7pE7lVf0RHIa0LiK3e36vegSDG9Svy6tpjPyj+J8ssqLvNU5p07j6u24UwAGQmpqQr0dXGQDbxhIPHu/8dYyB1U+fGP863Bed7lW/omYrrxBe8wM4O4gpiMxsdvsyYRyIUE3h/AYTA6FKP9dlPDbKe8CORt1Pf0cyP9iuBia8Lmp9ta+CtY/kXmcfqlTK7pqkzRbYGBTk8x31+uyNfg9fsX7ouF/g+vm/Z065U4ftwp1qQVfvMgc+zJDaHqG3i3N+bwsXFSr46dpGYU/vJRJRdwCNSg8XpmZvCEGF/KliuvVhvt7IH5+tkgjnYli15br7RnL3xe538K3M5qyuKv+nOiB6FvvF9gUzsb3oOPgTwuNfopq5i/1S+SMlCk5ce/JoT7SXQEUliIK+cOGgj/gFdr/w1G6iJUQEzzNJXRbiRwI4itEwe0uCIQiaVKE2gOep+0YLskck4RrQj/kli25dxLx/csmKtTnkDEEcuz4u0dNQDIaXk9FI06YvgWL/ytc=
  app: search-and-rescue-api
services:
  - postgresql
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
